spring:
  profiles: development
  jpa.hibernate.ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost/timesheet
    username: timesheet
    password: timesheet
    driver-class-name: com.mysql.jdbc.Driver
---
spring:
  profiles: production
  jpa.hibernate.ddl-auto: none
  datasource:
    url: TODO
    username: TODO
    password: TODO
    driver-class-name: TODO
---